### ISSUE TITLE
unknown type name ‘luaL_reg’

### ISSUE THREAD

**Issue by crazy4chrissi** [youlu-cn/luacrc16#1]
Comiling with Lua 5.2 causes the above error.

From http://lua-users.org/wiki/CompatibilityWithLuaFive :

luaL_reg (Lua 5.0) changed its name to luaL_Reg since Lua 5.1. This could be solved with conditional compilation: 

```
#if !defined LUA_VERSION_NUM
/* Lua 5.0 */
#define luaL_Reg luaL_reg
#endif
```

**Comment by youlu-cn** [comment]
Thanks, I will fix it
